export const i8: ref.Type<number>;
export const u8: ref.Type<number>;
export const i16: ref.Type<number>;
export const u16: ref.Type<number>;
export const i32: ref.Type<number>;
export const u32: ref.Type<number>;
export const i64: ref.Type<string | number>;
export const u64: ref.Type<string | number>;
export const usize: ref.Type<string | number>;
export const f32: ref.Type<number>;
export const f64: ref.Type<number>;
import ref from "ref-napi";
