export const VOID: ref.Type<void>;
export const ENUM: ref.Type<number>;
export const DWORD: ref.Type<string | number>;
export const WORD: ref.Type<number>;
export const SHORT: ref.Type<number>;
export const BYTE: ref.Type<number>;
export const WCHAR: ref.Type<number>;
export const ACCESS_MASK: ref.Type<number>;
export const ATOM: ref.Type<number>;
export const PVOID: ref.Type<ref.Pointer<string | number>>;
export const HANDLE: ref.Type<string | number>;
export const HANDLE_PVOID: ref.Type<ref.Pointer<string | number>>;
export const LONG_PTR: ref.Type<ref.Pointer<string | number>>;
export const ULONG_PTR: ref.Type<ref.Pointer<string | number>>;
export const BOOL: ref.Type<number>;
export const BOOLEAN: ref.Type<boolean>;
export const CALLBACK: any;
export const CCHAR: ref.Type<number>;
export const CHAR: ref.Type<number>;
export const COLORREF: ref.Type<string | number>;
export const DWORDLONG: ref.Type<string | number>;
export const DWORD_PTR: ref.Type<ref.Pointer<string | number>>;
export const DWORD32: ref.Type<number>;
export const DWORD64: ref.Type<string | number>;
export const FLOAT: ref.Type<number>;
export const HACCEL: ref.Type<string | number>;
export const HALF_PTR: ref.Type<number>;
export const HBITMAP: ref.Type<string | number>;
export const HBRUSH: ref.Type<string | number>;
export const HCOLORSPACE: ref.Type<string | number>;
export const HCONV: ref.Type<string | number>;
export const HCONVLIST: ref.Type<string | number>;
export const HCURSOR: ref.Type<string | number>;
export const HDC: ref.Type<string | number>;
export const HDDEDATA: ref.Type<string | number>;
export const HDESK: ref.Type<string | number>;
export const HDROP: ref.Type<string | number>;
export const HDWP: ref.Type<string | number>;
export const HENHMETAFILE: ref.Type<string | number>;
export const HFILE: ref.Type<string | number>;
export const HFONT: ref.Type<string | number>;
export const HGDIOBJ: ref.Type<string | number>;
export const HGLOBAL: ref.Type<string | number>;
export const HHOOK: ref.Type<string | number>;
export const HICON: ref.Type<string | number>;
export const HINSTANCE: ref.Type<string | number>;
export const HKEY: ref.Type<string | number>;
export const HKL: ref.Type<string | number>;
export const HLOCAL: ref.Type<string | number>;
export const HMENU: ref.Type<string | number>;
export const HMETAFILE: ref.Type<string | number>;
export const HMODULE: ref.Type<string | number>;
export const HMONITOR: ref.Type<string | number>;
export const HPALETTE: ref.Type<string | number>;
export const HPEN: ref.Type<string | number>;
export const HRESULT: ref.Type<string | number>;
export const HRGN: ref.Type<string | number>;
export const HRSRC: ref.Type<string | number>;
export const HSZ: ref.Type<string | number>;
export const HWINEVENTHOOK: ref.Type<string | number>;
export const HWINSTA: ref.Type<string | number>;
export const HWND: ref.Type<string | number>;
export const INT: ref.Type<number>;
export const INT_PTR: ref.Type<string | number>;
export const INT8: ref.Type<number>;
export const INT16: ref.Type<number>;
export const INT32: ref.Type<number>;
export const INT64: ref.Type<string | number>;
export const LANGID: ref.Type<number>;
export const LCID: ref.Type<string | number>;
export const LCTYPE: ref.Type<string | number>;
export const LGRPID: ref.Type<string | number>;
export const LONG: ref.Type<string | number>;
export const LONGLONG: ref.Type<string | number>;
export const LONG32: ref.Type<number>;
export const LONG64: ref.Type<string | number>;
export const LPARAM: ref.Type<ref.Pointer<string | number>>;
export const LPBOOL: ref.Type<number>;
export const LPBYTE: ref.Type<ref.Pointer<number>>;
export const LPCOLORREF: ref.Type<string | number>;
export const LPCSTR: ref.Type<string | null>;
export const LPCTSTR: ref.Type<string | null>;
export const LPCWSTR: ref.Type<string | null>;
export const LPVOID: ref.Type<ref.Pointer<void>>;
export const LPCVOID: ref.Type<ref.Pointer<void>>;
export const LPDWORD: ref.Type<ref.Pointer<number>>;
export const LPHANDLE: ref.Type<ref.Pointer<string | number>>;
export const LPINT: ref.Type<ref.Pointer<number>>;
export const LPLONG: ref.Type<ref.Pointer<number>>;
export const LPMSG: any;
export const LPPOINT: any;
export const LPSTR: ref.Type<ref.Pointer<number>>;
export const LPWSTR: ref.Type<ref.Pointer<number>>;
export const LPTSTR: ref.Type<ref.Pointer<number>>;
export const LPWORD: ref.Type<ref.Pointer<number>>;
export const LRESULT: ref.Type<ref.Pointer<string | number>>;
export const NTSTATUS: ref.Type<number>;
export const PBOOL: ref.Type<ref.Pointer<number>>;
export const PBOOLEAN: ref.Type<ref.Pointer<boolean>>;
export const PBYTE: ref.Type<ref.Pointer<number>>;
export const PCHAR: ref.Type<ref.Pointer<number>>;
export const PCSTR: ref.Type<ref.Pointer<number>>;
export const PCTSTR: ref.Type<ref.Pointer<number>>;
export const PCWSTR: ref.Type<ref.Pointer<number>>;
export const PDWORD: ref.Type<ref.Pointer<number>>;
export const PDWORDLONG: ref.Type<ref.Pointer<string | number>>;
export const PDWORD_PTR: ref.Type<ref.Pointer<string | number>>;
export const PDWORD32: ref.Type<ref.Pointer<number>>;
export const PDWORD64: ref.Type<ref.Pointer<string | number>>;
export const PFLOAT: ref.Type<ref.Pointer<number>>;
export const PHALF_PTR: any;
export const PHANDLE: ref.Type<ref.Pointer<ref.Pointer<string | number>>>;
export const PHKEY: ref.Type<ref.Pointer<ref.Pointer<string | number>>>;
export const PINT: ref.Type<ref.Pointer<number>>;
export const PINT_PTR: ref.Type<ref.Pointer<ref.Pointer<number>>>;
export const PINT8: ref.Type<ref.Pointer<number>>;
export const PINT16: ref.Type<ref.Pointer<number>>;
export const PINT32: ref.Type<ref.Pointer<number>>;
export const PINT64: ref.Type<ref.Pointer<string | number>>;
export const PLCID: ref.Type<ref.Pointer<number>>;
export const PLONG: ref.Type<ref.Pointer<string | number>>;
export const PLONGLONG: ref.Type<ref.Pointer<string | number>>;
export const PLONG_PTR: any;
export const PLONG32: ref.Type<ref.Pointer<number>>;
export const PLONG64: ref.Type<ref.Pointer<string | number>>;
export const POINTER_32: ref.Type<ref.Pointer<number>>;
export const POINTER_64: ref.Type<ref.Pointer<string | number>>;
export const POINTER_SIGNED: any;
export const POINTER_UNSIGNED: any;
export const PSHORT: ref.Type<ref.Pointer<number>>;
export const PSIZE_T: ref.Type<ref.Pointer<string | number>>;
export const PSSIZE_T: any;
export const PSTR: ref.Type<ref.Pointer<number>>;
export const PTBYTE: ref.Type<ref.Pointer<number>>;
export const PTCHAR: ref.Type<ref.Pointer<number>>;
export const PTSTR: ref.Type<ref.Pointer<number>>;
export const PUCHAR: any;
export const PUHALF_PTR: any;
export const PUINT: ref.Type<ref.Pointer<number>>;
export const PUINT_PTR: ref.Type<ref.Pointer<ref.Pointer<number>>>;
export const PUINT8: ref.Type<ref.Pointer<number>>;
export const PUINT16: ref.Type<ref.Pointer<number>>;
export const PUINT32: ref.Type<ref.Pointer<number>>;
export const PUINT64: ref.Type<ref.Pointer<string | number>>;
export const PULONG: ref.Type<ref.Pointer<number>>;
export const PULONGLONG: ref.Type<ref.Pointer<string | number>>;
export const PULONG_PTR: ref.Type<ref.Pointer<ref.Pointer<string | number>>>;
export const PULONG32: ref.Type<ref.Pointer<number>>;
export const PULONG64: ref.Type<ref.Pointer<string | number>>;
export const PUSHORT: ref.Type<ref.Pointer<number>>;
export const PWCHAR: ref.Type<ref.Pointer<number>>;
export const PWORD: ref.Type<ref.Pointer<number>>;
export const PWSTR: ref.Type<ref.Pointer<number>>;
export const QWORD: ref.Type<ref.Pointer<string | number>>;
export const SC_HANDLE: ref.Type<string | number>;
export const SC_LOCK: ref.Type<ref.Pointer<void>>;
export const SERVICE_STATUS_HANDLE: ref.Type<string | number>;
export const SIZE_T: ref.Type<ref.Pointer<string | number>>;
export const SSIZE_T: ref.Type<ref.Pointer<string | number>>;
export const TBYTE: ref.Type<number>;
export const TCHAR: ref.Type<number>;
export const UCHAR: ref.Type<number>;
export const UHALF_PTR: ref.Type<number>;
export const UINT: ref.Type<number>;
export const UINT_PTR: ref.Type<string | number>;
export const UINT8: ref.Type<number>;
export const UINT16: ref.Type<number>;
export const UINT32: ref.Type<number>;
export const UINT64: ref.Type<string | number>;
export const ULONG: ref.Type<string | number>;
export const ULONGLONG: ref.Type<string | number>;
export const ULONG32: ref.Type<number>;
export const ULONG64: ref.Type<string | number>;
export const USHORT: ref.Type<number>;
export const USN: ref.Type<string | number>;
export const WPARAM: ref.Type<string | number>;
import ref from "ref-napi";
